/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */
import type { ContactViewModel } from './contactViewModel';

export interface ContactViewModelListApiResponse {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  data?: ContactViewModel[] | null;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  message?: string | null;
}
