/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */

export type GetContactGetContactsCategory = typeof GetContactGetContactsCategory[keyof typeof GetContactGetContactsCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetContactGetContactsCategory = {
  CUSTOMERS: 'CUSTOMERS',
  SUPPLIERS: 'SUPPLIERS',
  CHARGEUR: 'CHARGEUR',
  RECEIVER: 'RECEIVER',
  SHIPPING_LINES: 'SHIPPING_LINES',
  BANK: 'BANK',
  SHIPPING_AGENCY11: 'SHIPPING_AGENCY11',
} as const;
