/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */
import type { GetContactGetContactsCategory } from './getContactGetContactsCategory';

export type GetContactGetContactsParams = {
contactName?: string;
category?: number;
contactNumber?: string;
pageNumber?: number;
pageSize?: number;
};
