/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */

export interface Int32ApiResponse {
  /** @nullable */
  code?: string | null;
  data?: number;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  message?: string | null;
}
