/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */

export type UpdateContactViewModelCategoriesItem = typeof UpdateContactViewModelCategoriesItem[keyof typeof UpdateContactViewModelCategoriesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateContactViewModelCategoriesItem = {
  CUSTOMERS: 'CUSTOMERS',
  SUPPLIERS: 'SUPPLIERS',
  CHARGEUR: 'CHARGEUR',
  RECEIVER: 'RECEIVER',
  SHIPPING_LINES: 'SHIPPING_LINES',
  BANK: 'BANK',
  SHIPPING_AGENCY11: 'SHIPPING_AGENCY11',
} as const;
