/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */
import type { UpdateContactViewModelCategoriesItem } from './updateContactViewModelCategoriesItem';

export interface UpdateContactViewModel {
  /** @nullable */
  addressCountry?: string | null;
  /** @nullable */
  categories?: string[] | null;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  createdBy?: number | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
}
