/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS Transport API
 * OpenAPI spec version: v1
 */

export interface CityViewModel {
  /** @nullable */
  country?: string | null;
  id?: number;
  /** @nullable */
  name?: string | null;
}
