/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS Transport API
 * OpenAPI spec version: v1
 */

export interface ContainerViewModel {
  packageId?: number;
  /** @nullable */
  packageName?: string | null;
}
