/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS.Shipment.API
 * OpenAPI spec version: 1.0
 */

export interface OrderDto {
  /** @nullable */
  buyerId?: number | null;
  /** @nullable */
  buyerName?: string | null;
  /** @nullable */
  city?: number | null;
  /** @nullable */
  cityIncotermTo?: number | null;
  /** @nullable */
  cityName?: string | null;
  /** @nullable */
  cityNameIncotermTo?: string | null;
  customerId?: number;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  departurePort?: number | null;
  /** @nullable */
  destinationPort?: number | null;
  /** @nullable */
  dischargePort?: string | null;
  /** @nullable */
  estimatedArrivalDate?: string | null;
  /** @nullable */
  estimatedDepartureDate?: string | null;
  exportation?: boolean;
  fiscalYear?: number;
  /** @nullable */
  incoTerm?: string | null;
  /** @nullable */
  incotermDestination?: string | null;
  /** @nullable */
  loadingPort?: string | null;
  orderId?: number;
  /** @nullable */
  orderNumber?: string | null;
  orderStatus?: number;
  /** @nullable */
  refBuyer?: string | null;
  /** @nullable */
  refClient?: string | null;
  /** @nullable */
  refSeller?: string | null;
  /** @nullable */
  refShippingAgent?: string | null;
  /** @nullable */
  sellerId?: number | null;
  /** @nullable */
  sellerName?: string | null;
  /** @nullable */
  shipId?: number | null;
  /** @nullable */
  shipLineId?: number | null;
  /** @nullable */
  shipName?: string | null;
  /** @nullable */
  shippingAgent?: number | null;
  /** @nullable */
  shippingAgentName?: string | null;
  /** @nullable */
  shippingLine?: string | null;
}
