/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS.Shipment.API
 * OpenAPI spec version: 1.0
 */

export interface ResponseOrdersListDto {
  /** @nullable */
  buyerName?: string | null;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  dischargePort?: string | null;
  /** @nullable */
  estimatedArrivalDate?: string | null;
  /** @nullable */
  estimatedDepartureDate?: string | null;
  /** @nullable */
  exportation?: boolean | null;
  fiscalYear?: number;
  /** @nullable */
  loadingPort?: string | null;
  orderDate?: string;
  orderId?: number;
  /** @nullable */
  orderNumber?: string | null;
  orderStatus?: number;
  /** @nullable */
  sellerName?: string | null;
  /** @nullable */
  shipName?: string | null;
  /** @nullable */
  shippingLine?: string | null;
}
