// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { PostApiQuotesData, PostApiQuotesError, PostApiQuotesResponse, GetApiQuotesData, GetApiQuotesError, GetApiQuotesResponse, GetApiQuotesByIdData, GetApiQuotesByIdError, GetApiQuotesByIdResponse, PutApiQuotesByIdData, PutApiQuotesByIdError, PutApiQuotesByIdResponse, DeleteApiQuotesByIdData, DeleteApiQuotesByIdError, DeleteApiQuotesByIdResponse, PostApiQuotesByIdApprovalData, PostApiQuotesByIdApprovalError, PostApiQuotesByIdApprovalResponse, PostApiDraftQuotesData, PostApiDraftQuotesError, PostApiDraftQuotesResponse, GetApiDraftQuotesData, GetApiDraftQuotesError, GetApiDraftQuotesResponse, GetApiDraftQuotesByIdData, GetApiDraftQuotesByIdError, GetApiDraftQuotesByIdResponse, PutApiDraftQuotesByIdData, PutApiDraftQuotesByIdError, PutApiDraftQuotesByIdResponse, DeleteApiDraftQuotesByIdData, DeleteApiDraftQuotesByIdError, DeleteApiDraftQuotesByIdResponse, PostApiDraftQuotesByIdOptionsData, PostApiDraftQuotesByIdOptionsError, PostApiDraftQuotesByIdOptionsResponse, DeleteApiDraftQuotesByIdOptionsByOptionIdData, DeleteApiDraftQuotesByIdOptionsByOptionIdError, DeleteApiDraftQuotesByIdOptionsByOptionIdResponse, PostApiDraftQuotesByIdFinalizeData, PostApiDraftQuotesByIdFinalizeError, PostApiDraftQuotesByIdFinalizeResponse } from './types.gen';

export const client = createClient(createConfig());

export const postApiQuotes = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiQuotesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiQuotesResponse, PostApiQuotesError, ThrowOnError>({
        ...options,
        url: '/api/quotes'
    });
};

export const getApiQuotes = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiQuotesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiQuotesResponse, GetApiQuotesError, ThrowOnError>({
        ...options,
        url: '/api/quotes'
    });
};

export const getApiQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiQuotesByIdResponse, GetApiQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/quotes/{id}'
    });
};

export const putApiQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PutApiQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).put<PutApiQuotesByIdResponse, PutApiQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/quotes/{id}'
    });
};

export const deleteApiQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiQuotesByIdResponse, DeleteApiQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/quotes/{id}'
    });
};

export const postApiQuotesByIdApproval = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PostApiQuotesByIdApprovalData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiQuotesByIdApprovalResponse, PostApiQuotesByIdApprovalError, ThrowOnError>({
        ...options,
        url: '/api/quotes/{id}/approval'
    });
};

export const postApiDraftQuotes = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiDraftQuotesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiDraftQuotesResponse, PostApiDraftQuotesError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes'
    });
};

export const getApiDraftQuotes = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiDraftQuotesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDraftQuotesResponse, GetApiDraftQuotesError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes'
    });
};

export const getApiDraftQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiDraftQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDraftQuotesByIdResponse, GetApiDraftQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}'
    });
};

export const putApiDraftQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PutApiDraftQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).put<PutApiDraftQuotesByIdResponse, PutApiDraftQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}'
    });
};

export const deleteApiDraftQuotesById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiDraftQuotesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiDraftQuotesByIdResponse, DeleteApiDraftQuotesByIdError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}'
    });
};

export const postApiDraftQuotesByIdOptions = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PostApiDraftQuotesByIdOptionsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiDraftQuotesByIdOptionsResponse, PostApiDraftQuotesByIdOptionsError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}/options'
    });
};

export const deleteApiDraftQuotesByIdOptionsByOptionId = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiDraftQuotesByIdOptionsByOptionIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiDraftQuotesByIdOptionsByOptionIdResponse, DeleteApiDraftQuotesByIdOptionsByOptionIdError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}/options/{optionId}'
    });
};

export const postApiDraftQuotesByIdFinalize = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PostApiDraftQuotesByIdFinalizeData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiDraftQuotesByIdFinalizeResponse, PostApiDraftQuotesByIdFinalizeError, ThrowOnError>({
        ...options,
        url: '/api/draft-quotes/{id}/finalize'
    });
};