/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS CRM API
 * OpenAPI spec version: v1
 */
import type {
  BooleanApiResponse,
  ContactViewModelApiResponse,
  ContactViewModelListApiResponse,
  CreateContactViewModel,
  GetContactGetContactsParams,
  Int32ApiResponse,
  UpdateContactViewModel
} from './schemas/crm'
import { axiosInstanceCrm } from './axiosInstanceCrm';




  export const getLisCrmApi = () => {
const getContactGetContacts = (
    params?: GetContactGetContactsParams,
 ) => {
      return axiosInstanceCrm<ContactViewModelListApiResponse>(
      {url: `/Contact/GetContacts`, method: 'GET',
        params
    },
      );
    }
  
const postContactCreateContact = (
    createContactViewModel: CreateContactViewModel,
 ) => {
      return axiosInstanceCrm<Int32ApiResponse>(
      {url: `/Contact/CreateContact`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContactViewModel
    },
      );
    }
  
const getContactGetContactByIdId = (
    id: number,
 ) => {
      return axiosInstanceCrm<ContactViewModelApiResponse>(
      {url: `/Contact/GetContactById/${id}`, method: 'GET'
    },
      );
    }
  
const putContactUpdateContactId = (
    id: number,
    updateContactViewModel: UpdateContactViewModel,
 ) => {
      return axiosInstanceCrm<BooleanApiResponse>(
      {url: `/Contact/UpdateContact/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateContactViewModel
    },
      );
    }
  
const deleteContactDeleteContactId = (
    id: number,
 ) => {
      return axiosInstanceCrm<BooleanApiResponse>(
      {url: `/Contact/DeleteContact/${id}`, method: 'DELETE'
    },
      );
    }
  
return {getContactGetContacts,postContactCreateContact,getContactGetContactByIdId,putContactUpdateContactId,deleteContactDeleteContactId}};
export type GetContactGetContactsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLisCrmApi>['getContactGetContacts']>>>
export type PostContactCreateContactResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLisCrmApi>['postContactCreateContact']>>>
export type GetContactGetContactByIdIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLisCrmApi>['getContactGetContactByIdId']>>>
export type PutContactUpdateContactIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLisCrmApi>['putContactUpdateContactId']>>>
export type DeleteContactDeleteContactIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLisCrmApi>['deleteContactDeleteContactId']>>>
