/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */
import type {
  Assignee,
  ChangeStatusRequest,
  EmailConfig,
  GetApiAssigneeParams,
  GetApiRequestParams,
  GetApiRequestQuoteHistoryParams,
  GetApiRequestQuoteNotesParams,
  GraphApiUser,
  HSCodeLIS,
  PostApiEmailBody,
  PostApiFileUploadBody,
  PostApiSmsSendParams,
  PostWhatsAppSendmessageParams,
  RequestQuote,
  RequestQuoteHistory,
  RequestQuoteNote
} from './schemas/quote'
import { axiosInstanceQuote } from './axiosInstanceQuote';




  export const getRequestQuote = () => {
const getApiAssignee = (
    params?: GetApiAssigneeParams,
 ) => {
      return axiosInstanceQuote<Assignee[]>(
      {url: `/api/Assignee`, method: 'GET',
        params
    },
      );
    }
  
const postApiAssignee = (
    assignee: Assignee,
 ) => {
      return axiosInstanceQuote<Assignee>(
      {url: `/api/Assignee`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignee
    },
      );
    }
  
const getApiAssigneeId = (
    id: number,
 ) => {
      return axiosInstanceQuote<Assignee>(
      {url: `/api/Assignee/${id}`, method: 'GET'
    },
      );
    }
  
const putApiAssigneeId = (
    id: number,
    assignee: Assignee,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Assignee/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: assignee
    },
      );
    }
  
const deleteApiAssigneeId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Assignee/${id}`, method: 'DELETE'
    },
      );
    }
  
const putApiAssigneeRequestQuoteIdAssigneeId = (
    requestQuoteId: number,
    assigneeId: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Assignee/${requestQuoteId}/${assigneeId}`, method: 'PUT'
    },
      );
    }
  
const putApiAssigneeUnassignRequestQuoteId = (
    requestQuoteId: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Assignee/unassign/${requestQuoteId}`, method: 'PUT'
    },
      );
    }
  
const postApiEmail = (
    postApiEmailBody: PostApiEmailBody,
 ) => {const formData = new FormData();
if(postApiEmailBody.From !== undefined) {
 formData.append('From', postApiEmailBody.From)
 }
if(postApiEmailBody.To !== undefined) {
 formData.append('To', postApiEmailBody.To)
 }
if(postApiEmailBody.Subject !== undefined) {
 formData.append('Subject', postApiEmailBody.Subject)
 }
if(postApiEmailBody.HtmlContent !== undefined) {
 formData.append('HtmlContent', postApiEmailBody.HtmlContent)
 }
if(postApiEmailBody.Attachments !== undefined) {
 postApiEmailBody.Attachments.forEach(value => formData.append('Attachments', value));
 }

      return axiosInstanceQuote<void>(
      {url: `/api/Email`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
const getEmailConfig = (
    
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/EmailConfig`, method: 'GET'
    },
      );
    }
  
const putEmailConfig = (
    emailConfig: EmailConfig,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/EmailConfig`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: emailConfig
    },
      );
    }
  
const postEmailConfig = (
    emailConfig: EmailConfig,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/EmailConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailConfig
    },
      );
    }
  
const postApiFileUpload = (
    postApiFileUploadBody: PostApiFileUploadBody,
 ) => {const formData = new FormData();
if(postApiFileUploadBody.file !== undefined) {
 formData.append('file', postApiFileUploadBody.file)
 }

      return axiosInstanceQuote<void>(
      {url: `/api/File/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
const getApiFileBlobName = (
    blobName: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/File/${blobName}`, method: 'GET'
    },
      );
    }
  
const deleteApiFileBlobName = (
    blobName: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/File/${blobName}`, method: 'DELETE'
    },
      );
    }
  
const getApiFileUriBlobName = (
    blobName: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/File/uri/${blobName}`, method: 'GET'
    },
      );
    }
  
const getApiHSCodeLIS = (
    
 ) => {
      return axiosInstanceQuote<HSCodeLIS[]>(
      {url: `/api/HSCodeLIS`, method: 'GET'
    },
      );
    }
  
const postApiHSCodeLIS = (
    hSCodeLIS: HSCodeLIS,
 ) => {
      return axiosInstanceQuote<HSCodeLIS>(
      {url: `/api/HSCodeLIS`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hSCodeLIS
    },
      );
    }
  
const getApiHSCodeLISId = (
    id: number,
 ) => {
      return axiosInstanceQuote<HSCodeLIS>(
      {url: `/api/HSCodeLIS/${id}`, method: 'GET'
    },
      );
    }
  
const putApiHSCodeLISId = (
    id: number,
    hSCodeLIS: HSCodeLIS,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/HSCodeLIS/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hSCodeLIS
    },
      );
    }
  
const deleteApiHSCodeLISId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/HSCodeLIS/${id}`, method: 'DELETE'
    },
      );
    }
  
const getApiRequest = (
    params?: GetApiRequestParams,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request`, method: 'GET',
        params
    },
      );
    }
  
const postApiRequest = (
    requestQuote: RequestQuote,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestQuote
    },
      );
    }
  
const getApiRequestId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request/${id}`, method: 'GET'
    },
      );
    }
  
const putApiRequestId = (
    id: number,
    requestQuote: RequestQuote,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: requestQuote
    },
      );
    }
  
const deleteApiRequestId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request/${id}`, method: 'DELETE'
    },
      );
    }
  
const putApiRequestIdChangeStatus = (
    id: number,
    changeStatusRequest: ChangeStatusRequest,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Request/${id}/changeStatus`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changeStatusRequest
    },
      );
    }
  
const getApiRequestQuoteHistory = (
    params?: GetApiRequestQuoteHistoryParams,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteHistory`, method: 'GET',
        params
    },
      );
    }
  
const postApiRequestQuoteHistory = (
    requestQuoteHistory: RequestQuoteHistory,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteHistory`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestQuoteHistory
    },
      );
    }
  
const getApiRequestQuoteHistoryId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteHistory/${id}`, method: 'GET'
    },
      );
    }
  
const putApiRequestQuoteHistoryId = (
    id: number,
    requestQuoteHistory: RequestQuoteHistory,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteHistory/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: requestQuoteHistory
    },
      );
    }
  
const deleteApiRequestQuoteHistoryId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteHistory/${id}`, method: 'DELETE'
    },
      );
    }
  
const getApiRequestQuoteNotes = (
    params?: GetApiRequestQuoteNotesParams,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteNotes`, method: 'GET',
        params
    },
      );
    }
  
const postApiRequestQuoteNotes = (
    requestQuoteNote: RequestQuoteNote,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteNotes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestQuoteNote
    },
      );
    }
  
const getApiRequestQuoteNotesId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteNotes/${id}`, method: 'GET'
    },
      );
    }
  
const putApiRequestQuoteNotesId = (
    id: number,
    requestQuoteNote: RequestQuoteNote,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteNotes/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: requestQuoteNote
    },
      );
    }
  
const deleteApiRequestQuoteNotesId = (
    id: number,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/RequestQuoteNotes/${id}`, method: 'DELETE'
    },
      );
    }
  
const postApiSmsSend = (
    params?: PostApiSmsSendParams,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Sms/send`, method: 'POST',
        params
    },
      );
    }
  
const getApiTrackingTrackingNumber = (
    trackingNumber: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/api/Tracking/${trackingNumber}`, method: 'GET'
    },
      );
    }
  
const postUserGroupUsersUserId = (
    userId: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/UserGroup/users/${userId}`, method: 'POST'
    },
      );
    }
  
const deleteUserGroupUsersUserId = (
    userId: string,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/UserGroup/users/${userId}`, method: 'DELETE'
    },
      );
    }
  
const getUserGroupUsers = (
    
 ) => {
      return axiosInstanceQuote<GraphApiUser[]>(
      {url: `/UserGroup/users`, method: 'GET'
    },
      );
    }
  
const postWhatsAppSendmessage = (
    params?: PostWhatsAppSendmessageParams,
 ) => {
      return axiosInstanceQuote<void>(
      {url: `/WhatsApp/sendmessage`, method: 'POST',
        params
    },
      );
    }
  
return {getApiAssignee,postApiAssignee,getApiAssigneeId,putApiAssigneeId,deleteApiAssigneeId,putApiAssigneeRequestQuoteIdAssigneeId,putApiAssigneeUnassignRequestQuoteId,postApiEmail,getEmailConfig,putEmailConfig,postEmailConfig,postApiFileUpload,getApiFileBlobName,deleteApiFileBlobName,getApiFileUriBlobName,getApiHSCodeLIS,postApiHSCodeLIS,getApiHSCodeLISId,putApiHSCodeLISId,deleteApiHSCodeLISId,getApiRequest,postApiRequest,getApiRequestId,putApiRequestId,deleteApiRequestId,putApiRequestIdChangeStatus,getApiRequestQuoteHistory,postApiRequestQuoteHistory,getApiRequestQuoteHistoryId,putApiRequestQuoteHistoryId,deleteApiRequestQuoteHistoryId,getApiRequestQuoteNotes,postApiRequestQuoteNotes,getApiRequestQuoteNotesId,putApiRequestQuoteNotesId,deleteApiRequestQuoteNotesId,postApiSmsSend,getApiTrackingTrackingNumber,postUserGroupUsersUserId,deleteUserGroupUsersUserId,getUserGroupUsers,postWhatsAppSendmessage}};
export type GetApiAssigneeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiAssignee']>>>
export type PostApiAssigneeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiAssignee']>>>
export type GetApiAssigneeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiAssigneeId']>>>
export type PutApiAssigneeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiAssigneeId']>>>
export type DeleteApiAssigneeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiAssigneeId']>>>
export type PutApiAssigneeRequestQuoteIdAssigneeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiAssigneeRequestQuoteIdAssigneeId']>>>
export type PutApiAssigneeUnassignRequestQuoteIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiAssigneeUnassignRequestQuoteId']>>>
export type PostApiEmailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiEmail']>>>
export type GetEmailConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getEmailConfig']>>>
export type PutEmailConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putEmailConfig']>>>
export type PostEmailConfigResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postEmailConfig']>>>
export type PostApiFileUploadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiFileUpload']>>>
export type GetApiFileBlobNameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiFileBlobName']>>>
export type DeleteApiFileBlobNameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiFileBlobName']>>>
export type GetApiFileUriBlobNameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiFileUriBlobName']>>>
export type GetApiHSCodeLISResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiHSCodeLIS']>>>
export type PostApiHSCodeLISResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiHSCodeLIS']>>>
export type GetApiHSCodeLISIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiHSCodeLISId']>>>
export type PutApiHSCodeLISIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiHSCodeLISId']>>>
export type DeleteApiHSCodeLISIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiHSCodeLISId']>>>
export type GetApiRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequest']>>>
export type PostApiRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiRequest']>>>
export type GetApiRequestIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequestId']>>>
export type PutApiRequestIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiRequestId']>>>
export type DeleteApiRequestIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiRequestId']>>>
export type PutApiRequestIdChangeStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiRequestIdChangeStatus']>>>
export type GetApiRequestQuoteHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequestQuoteHistory']>>>
export type PostApiRequestQuoteHistoryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiRequestQuoteHistory']>>>
export type GetApiRequestQuoteHistoryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequestQuoteHistoryId']>>>
export type PutApiRequestQuoteHistoryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiRequestQuoteHistoryId']>>>
export type DeleteApiRequestQuoteHistoryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiRequestQuoteHistoryId']>>>
export type GetApiRequestQuoteNotesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequestQuoteNotes']>>>
export type PostApiRequestQuoteNotesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiRequestQuoteNotes']>>>
export type GetApiRequestQuoteNotesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiRequestQuoteNotesId']>>>
export type PutApiRequestQuoteNotesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['putApiRequestQuoteNotesId']>>>
export type DeleteApiRequestQuoteNotesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteApiRequestQuoteNotesId']>>>
export type PostApiSmsSendResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postApiSmsSend']>>>
export type GetApiTrackingTrackingNumberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getApiTrackingTrackingNumber']>>>
export type PostUserGroupUsersUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postUserGroupUsersUserId']>>>
export type DeleteUserGroupUsersUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['deleteUserGroupUsersUserId']>>>
export type GetUserGroupUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['getUserGroupUsers']>>>
export type PostWhatsAppSendmessageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRequestQuote>['postWhatsAppSendmessage']>>>
