/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS.Shipment.API
 * OpenAPI spec version: 1.0
 */
import type {
  GetOrdersParams,
  OrderDto,
  ResponseOrdersListDto
} from './schemas/shipment'
import { axiosInstanceShipment } from './axiosInstanceShipment';




  export const getLISShipmentAPI = () => {
/**
 * @summary Get list orders in fonction parameters
 */
const getOrders = (
    params?: GetOrdersParams,
 ) => {
      return axiosInstanceShipment<ResponseOrdersListDto[]>(
      {url: `/Order/orders`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Get order by id
 */
const getOrderById = (
    orderId: number,
 ) => {
      return axiosInstanceShipment<OrderDto>(
      {url: `/Order/${orderId}`, method: 'GET'
    },
      );
    }
  
return {getOrders,getOrderById}};
export type GetOrdersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLISShipmentAPI>['getOrders']>>>
export type GetOrderByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLISShipmentAPI>['getOrderById']>>>
