// This file is auto-generated by @hey-api/openapi-ts

export type OrderDto = {
    orderId?: number;
    orderNumber?: (string) | null;
    customerId?: number;
    sellerId?: (number) | null;
    buyerId?: (number) | null;
    customerName?: (string) | null;
    sellerName?: (string) | null;
    buyerName?: (string) | null;
    refClient?: (string) | null;
    refSeller?: (string) | null;
    refBuyer?: (string) | null;
    incoTerm?: (string) | null;
    incotermDestination?: (string) | null;
    fiscalYear?: number;
    exportation?: boolean;
    city?: (number) | null;
    cityName?: (string) | null;
    cityIncotermTo?: (number) | null;
    cityNameIncotermTo?: (string) | null;
    shippingLine?: (string) | null;
    shipLineId?: (number) | null;
    orderStatus?: number;
    refShippingAgent?: (string) | null;
    shippingAgentName?: (string) | null;
    shippingAgent?: (number) | null;
    shipName?: (string) | null;
    shipId?: (number) | null;
    loadingPort?: (string) | null;
    departurePort?: (number) | null;
    dischargePort?: (string) | null;
    destinationPort?: (number) | null;
    estimatedDepartureDate?: (string) | null;
    estimatedArrivalDate?: (string) | null;
};

export type ResponseOrdersListDto = {
    orderId?: number;
    orderNumber?: (string) | null;
    orderDate?: string;
    fiscalYear?: number;
    customerName?: (string) | null;
    sellerName?: (string) | null;
    buyerName?: (string) | null;
    loadingPort?: (string) | null;
    dischargePort?: (string) | null;
    estimatedDepartureDate?: (string) | null;
    estimatedArrivalDate?: (string) | null;
    shipName?: (string) | null;
    shippingLine?: (string) | null;
    exportation?: (boolean) | null;
    orderStatus?: number;
};

export type GetOrdersData = {
    query?: {
        Fiscal?: number;
        Month?: number;
    };
};

export type GetOrdersResponse = (Array<ResponseOrdersListDto>);

export type GetOrdersError = (unknown);

export type GetOrderByIdData = {
    path: {
        /**
         * Identifiant
         */
        orderId: number;
    };
};

export type GetOrderByIdResponse = (OrderDto);

export type GetOrderByIdError = (unknown);