/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export interface Assignee {
  /** @minLength 1 */
  email: string;
  id?: number;
  /** @nullable */
  idUser?: string | null;
  /** @minLength 1 */
  name: string;
}
