/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export interface Container {
  /** @nullable */
  containers?: string | null;
  id?: number;
  quantity?: number;
}
