/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export interface EmailConfig {
  /** @minLength 1 */
  adminEmail: string;
  /** @minLength 1 */
  fromEmail: string;
  id?: number;
}
