/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type GetApiRequestParams = {
Arrival?: string;
Departure?: string;
CargoType?: string;
Status?: string;
Tags?: string;
Search?: string;
Creator?: string;
AssigneeId?: number;
CreatedAtStart?: string;
CreatedAtEnd?: string;
UpdatedAtStart?: string;
UpdatedAtEnd?: string;
PackingType?: string;
ClientNumber?: string;
};
