/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */
import type { NoteType } from './noteType';

export type GetApiRequestQuoteNotesParams = {
requestQuoteId?: number;
createdAtFrom?: string;
createdAtTo?: string;
isInternal?: boolean;
noteType?: NoteType;
userIdFilter?: string;
};
