/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type GetApiRequestQuoteHistoryParams = {
startDate?: string;
endDate?: string;
assigneeId?: number;
requestQuoteId?: number;
};
