/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export interface HSCodeLIS {
  /** @nullable */
  _4_digit_categories?: string | null;
  hS_Code?: number;
  /** @nullable */
  product_description_En?: string | null;
  /** @nullable */
  product_description_Fr?: string | null;
  /** @nullable */
  product_description_NL?: string | null;
}
