/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type NoteType = typeof NoteType[keyof typeof NoteType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoteType = {
  Automatic: 'Automatic',
  General: 'General',
  CustomStatusChange: 'CustomStatusChange',
  InformationRequest: 'InformationRequest',
} as const;
