/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type PostApiEmailBody = {
  Attachments?: Blob[];
  From?: string;
  HtmlContent?: string;
  Subject?: string;
  To?: string;
};
