/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type PostWhatsAppSendmessageParams = {
toPhoneNumber?: string;
messageText?: string;
fromWhatsAppNumber?: string;
};
