/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */
import type { NoteType } from './noteType';

export interface RequestQuoteNote {
  /** @nullable */
  content?: string | null;
  createdAt?: string;
  /** @nullable */
  email?: string | null;
  id?: number;
  /** @nullable */
  idUser?: string | null;
  isInternal?: boolean;
  noteType?: NoteType;
  requestQuoteId?: number;
  /** @nullable */
  subject?: string | null;
}
