/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */
import type { Assignee } from './assignee';
import type { TypeOfCargo } from './typeOfCargo';
import type { Container } from './container';
import type { RequestQuoteNote } from './requestQuoteNote';
import type { StatusRequest } from './statusRequest';
import type { Unit } from './unit';

export interface RequestQuote {
  /** @minLength 1 */
  arrival: string;
  assignee?: Assignee;
  /** @nullable */
  assigneeId?: number | null;
  cargoType: TypeOfCargo;
  /** @nullable */
  clientNumber?: string | null;
  /** @nullable */
  containers?: Container[] | null;
  /** @nullable */
  containersJson?: string | null;
  /** @nullable */
  createdAt?: string | null;
  /** @nullable */
  creator?: string | null;
  /** @minLength 1 */
  departure: string;
  /** @nullable */
  detail?: string | null;
  /** @minLength 1 */
  email: string;
  id?: number;
  /** @nullable */
  notes?: RequestQuoteNote[] | null;
  /** @nullable */
  packingType?: string | null;
  quantity: number;
  status?: StatusRequest;
  /** @nullable */
  tags?: string | null;
  /** @nullable */
  trackingNumber?: string | null;
  /** @nullable */
  units?: Unit[] | null;
  /** @nullable */
  unitsJson?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  /** @minLength 1 */
  whatsapp: string;
}
