/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type StatusRequest = typeof StatusRequest[keyof typeof StatusRequest];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusRequest = {
  New: 'New',
  EnAttente: 'EnAttente',
  Valider: 'Valider',
  Rejeter: 'Rejeter',
  EnCoursDeTraitement: 'EnCoursDeTraitement',
  EnTransit: 'EnTransit',
  EnDouane: 'EnDouane',
  LivraisonEnCours: 'LivraisonEnCours',
  Livre: 'Livre',
  Annule: 'Annule',
  Retour: 'Retour',
  Problème: 'Problème',
  EnAttenteDeFacturation: 'EnAttenteDeFacturation',
} as const;
