/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * RequestQuote
 * OpenAPI spec version: v1
 */

export type TypeOfCargo = typeof TypeOfCargo[keyof typeof TypeOfCargo];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeOfCargo = {
  Container: 'Container',
  Conventional: 'Conventional',
  RollOnRollOff: 'RollOnRollOff',
} as const;
