// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { PostApiHaulageHaulageData, PostApiHaulageHaulageError, PostApiHaulageHaulageResponse, PutApiHaulageHaulageByIdData, PutApiHaulageHaulageByIdError, PutApiHaulageHaulageByIdResponse, GetApiHaulageHaulageByIdData, GetApiHaulageHaulageByIdError, GetApiHaulageHaulageByIdResponse, GetApiHaulageHaulagesError, GetApiHaulageHaulagesResponse, DeleteApiHaulageDeleteHaulageByIdData, DeleteApiHaulageDeleteHaulageByIdError, DeleteApiHaulageDeleteHaulageByIdResponse, GetApiMiscellaneousMiscellaneousError, GetApiMiscellaneousMiscellaneousResponse, PostApiMiscellaneousMiscellaneousData, PostApiMiscellaneousMiscellaneousError, PostApiMiscellaneousMiscellaneousResponse, GetApiMiscellaneousMiscellaneousByIdData, GetApiMiscellaneousMiscellaneousByIdError, GetApiMiscellaneousMiscellaneousByIdResponse, PutApiMiscellaneousMiscellaneousByIdData, PutApiMiscellaneousMiscellaneousByIdError, PutApiMiscellaneousMiscellaneousByIdResponse, DeleteApiMiscellaneousDeleteMiscellaneousByIdData, DeleteApiMiscellaneousDeleteMiscellaneousByIdError, DeleteApiMiscellaneousDeleteMiscellaneousByIdResponse, GetApiPricingHaulagesOfferRequestData, GetApiPricingHaulagesOfferRequestError, GetApiPricingHaulagesOfferRequestResponse, GetApiPricingMiscellaneoussOffersRequestData, GetApiPricingMiscellaneoussOffersRequestError, GetApiPricingMiscellaneoussOffersRequestResponse, GetApiPricingSeaFreightsOffersRequestData, GetApiPricingSeaFreightsOffersRequestError, GetApiPricingSeaFreightsOffersRequestResponse, PostApiSeaFreightSeaFreightData, PostApiSeaFreightSeaFreightError, PostApiSeaFreightSeaFreightResponse, GetApiSeaFreightGetSeaFreightsData, GetApiSeaFreightGetSeaFreightsError, GetApiSeaFreightGetSeaFreightsResponse, GetApiSeaFreightSeaFreightByIdData, GetApiSeaFreightSeaFreightByIdError, GetApiSeaFreightSeaFreightByIdResponse, DeleteApiSeaFreightDeleteSeaFreightPriceByIdData, DeleteApiSeaFreightDeleteSeaFreightPriceByIdError, DeleteApiSeaFreightDeleteSeaFreightPriceByIdResponse } from './types.gen';

export const client = createClient(createConfig());

export const postApiHaulageHaulage = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiHaulageHaulageData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiHaulageHaulageResponse, PostApiHaulageHaulageError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulage'
    });
};

export const putApiHaulageHaulageById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PutApiHaulageHaulageByIdData, ThrowOnError>) => {
    return (options?.client ?? client).put<PutApiHaulageHaulageByIdResponse, PutApiHaulageHaulageByIdError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulage/{id}'
    });
};

export const getApiHaulageHaulageById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiHaulageHaulageByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiHaulageHaulageByIdResponse, GetApiHaulageHaulageByIdError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulage/{id}'
    });
};

export const getApiHaulageHaulages = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiHaulageHaulagesResponse, GetApiHaulageHaulagesError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulages'
    });
};

export const deleteApiHaulageDeleteHaulageById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiHaulageDeleteHaulageByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiHaulageDeleteHaulageByIdResponse, DeleteApiHaulageDeleteHaulageByIdError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/DeleteHaulage/{id}'
    });
};

export const getApiMiscellaneousMiscellaneous = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMiscellaneousMiscellaneousResponse, GetApiMiscellaneousMiscellaneousError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous'
    });
};

export const postApiMiscellaneousMiscellaneous = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiMiscellaneousMiscellaneousData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiMiscellaneousMiscellaneousResponse, PostApiMiscellaneousMiscellaneousError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous'
    });
};

export const getApiMiscellaneousMiscellaneousById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiMiscellaneousMiscellaneousByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMiscellaneousMiscellaneousByIdResponse, GetApiMiscellaneousMiscellaneousByIdError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous/{id}'
    });
};

export const putApiMiscellaneousMiscellaneousById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PutApiMiscellaneousMiscellaneousByIdData, ThrowOnError>) => {
    return (options?.client ?? client).put<PutApiMiscellaneousMiscellaneousByIdResponse, PutApiMiscellaneousMiscellaneousByIdError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous/{id}'
    });
};

export const deleteApiMiscellaneousDeleteMiscellaneousById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiMiscellaneousDeleteMiscellaneousByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiMiscellaneousDeleteMiscellaneousByIdResponse, DeleteApiMiscellaneousDeleteMiscellaneousByIdError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/DeleteMiscellaneous/{id}'
    });
};

export const getApiPricingHaulagesOfferRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingHaulagesOfferRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingHaulagesOfferRequestResponse, GetApiPricingHaulagesOfferRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/HaulagesOfferRequest'
    });
};

export const getApiPricingMiscellaneoussOffersRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingMiscellaneoussOffersRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingMiscellaneoussOffersRequestResponse, GetApiPricingMiscellaneoussOffersRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/MiscellaneoussOffersRequest'
    });
};

export const getApiPricingSeaFreightsOffersRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingSeaFreightsOffersRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingSeaFreightsOffersRequestResponse, GetApiPricingSeaFreightsOffersRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/SeaFreightsOffersRequest'
    });
};

export const postApiSeaFreightSeaFreight = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiSeaFreightSeaFreightData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiSeaFreightSeaFreightResponse, PostApiSeaFreightSeaFreightError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/SeaFreight'
    });
};

export const getApiSeaFreightGetSeaFreights = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiSeaFreightGetSeaFreightsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiSeaFreightGetSeaFreightsResponse, GetApiSeaFreightGetSeaFreightsError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/GetSeaFreights'
    });
};

export const getApiSeaFreightSeaFreightById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetApiSeaFreightSeaFreightByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiSeaFreightSeaFreightByIdResponse, GetApiSeaFreightSeaFreightByIdError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/SeaFreight/{id}'
    });
};

export const deleteApiSeaFreightDeleteSeaFreightPriceById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiSeaFreightDeleteSeaFreightPriceByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiSeaFreightDeleteSeaFreightPriceByIdResponse, DeleteApiSeaFreightDeleteSeaFreightPriceByIdError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/DeleteSeaFreightPrice/{id}'
    });
};