// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { PostApiHaulageHaulageData, PostApiHaulageHaulageError, PostApiHaulageHaulageResponse, GetApiHaulageHaulageData, GetApiHaulageHaulageError, GetApiHaulageHaulageResponse, GetApiHaulageHaulagesData, GetApiHaulageHaulagesError, GetApiHaulageHaulagesResponse, DeleteApiHaulageDeleteHaulageData, DeleteApiHaulageDeleteHaulageError, DeleteApiHaulageDeleteHaulageResponse, GetApiMiscellaneousMiscellaneousData, GetApiMiscellaneousMiscellaneousError, GetApiMiscellaneousMiscellaneousResponse, PostApiMiscellaneousMiscellaneousData, PostApiMiscellaneousMiscellaneousError, PostApiMiscellaneousMiscellaneousResponse, DeleteApiMiscellaneousDeleteMiscellaneousByIdData, DeleteApiMiscellaneousDeleteMiscellaneousByIdError, DeleteApiMiscellaneousDeleteMiscellaneousByIdResponse, GetApiPricingHaulagesOfferRequestData, GetApiPricingHaulagesOfferRequestError, GetApiPricingHaulagesOfferRequestResponse, GetApiPricingMiscellaneoussOffersRequestData, GetApiPricingMiscellaneoussOffersRequestError, GetApiPricingMiscellaneoussOffersRequestResponse, GetApiPricingSeaFreightsOffersRequestData, GetApiPricingSeaFreightsOffersRequestError, GetApiPricingSeaFreightsOffersRequestResponse, PostApiSeaFreightSeaFreightData, PostApiSeaFreightSeaFreightError, PostApiSeaFreightSeaFreightResponse, GetApiSeaFreightSeaFreightData, GetApiSeaFreightSeaFreightError, GetApiSeaFreightSeaFreightResponse, GetApiSeaFreightGetSeaFreightsData, GetApiSeaFreightGetSeaFreightsError, GetApiSeaFreightGetSeaFreightsResponse, DeleteApiSeaFreightDeleteSeaFreightPriceData, DeleteApiSeaFreightDeleteSeaFreightPriceError, DeleteApiSeaFreightDeleteSeaFreightPriceResponse } from './types.gen';

export const client = createClient(createConfig());

export const postApiHaulageHaulage = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiHaulageHaulageData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiHaulageHaulageResponse, PostApiHaulageHaulageError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulage'
    });
};

export const getApiHaulageHaulage = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiHaulageHaulageData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiHaulageHaulageResponse, GetApiHaulageHaulageError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulage'
    });
};

export const getApiHaulageHaulages = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiHaulageHaulagesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiHaulageHaulagesResponse, GetApiHaulageHaulagesError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/Haulages'
    });
};

export const deleteApiHaulageDeleteHaulage = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<DeleteApiHaulageDeleteHaulageData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiHaulageDeleteHaulageResponse, DeleteApiHaulageDeleteHaulageError, ThrowOnError>({
        ...options,
        url: '/api/Haulage/DeleteHaulage'
    });
};

export const getApiMiscellaneousMiscellaneous = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiMiscellaneousMiscellaneousData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMiscellaneousMiscellaneousResponse, GetApiMiscellaneousMiscellaneousError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous'
    });
};

export const postApiMiscellaneousMiscellaneous = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiMiscellaneousMiscellaneousData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiMiscellaneousMiscellaneousResponse, PostApiMiscellaneousMiscellaneousError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/Miscellaneous'
    });
};

export const deleteApiMiscellaneousDeleteMiscellaneousById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteApiMiscellaneousDeleteMiscellaneousByIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiMiscellaneousDeleteMiscellaneousByIdResponse, DeleteApiMiscellaneousDeleteMiscellaneousByIdError, ThrowOnError>({
        ...options,
        url: '/api/Miscellaneous/DeleteMiscellaneous/{id}'
    });
};

export const getApiPricingHaulagesOfferRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingHaulagesOfferRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingHaulagesOfferRequestResponse, GetApiPricingHaulagesOfferRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/HaulagesOfferRequest'
    });
};

export const getApiPricingMiscellaneoussOffersRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingMiscellaneoussOffersRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingMiscellaneoussOffersRequestResponse, GetApiPricingMiscellaneoussOffersRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/MiscellaneoussOffersRequest'
    });
};

export const getApiPricingSeaFreightsOffersRequest = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiPricingSeaFreightsOffersRequestData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPricingSeaFreightsOffersRequestResponse, GetApiPricingSeaFreightsOffersRequestError, ThrowOnError>({
        ...options,
        url: '/api/Pricing/SeaFreightsOffersRequest'
    });
};

export const postApiSeaFreightSeaFreight = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostApiSeaFreightSeaFreightData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiSeaFreightSeaFreightResponse, PostApiSeaFreightSeaFreightError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/SeaFreight'
    });
};

export const getApiSeaFreightSeaFreight = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiSeaFreightSeaFreightData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiSeaFreightSeaFreightResponse, GetApiSeaFreightSeaFreightError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/SeaFreight'
    });
};

export const getApiSeaFreightGetSeaFreights = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetApiSeaFreightGetSeaFreightsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiSeaFreightGetSeaFreightsResponse, GetApiSeaFreightGetSeaFreightsError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/GetSeaFreights'
    });
};

export const deleteApiSeaFreightDeleteSeaFreightPrice = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<DeleteApiSeaFreightDeleteSeaFreightPriceData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiSeaFreightDeleteSeaFreightPriceResponse, DeleteApiSeaFreightDeleteSeaFreightPriceError, ThrowOnError>({
        ...options,
        url: '/api/SeaFreight/DeleteSeaFreightPrice'
    });
};