// This file is auto-generated by @hey-api/openapi-ts

export type HaulageGridGetViewModel = {
    loadingCity?: (string) | null;
    loadingPort?: (string) | null;
    hauliers?: Array<HaulageSupplierViewModel> | null;
};

export type HaulageOfferViewModel = {
    id?: (string) | null;
    haulierId?: number;
    haulierName?: (string) | null;
    validUntil?: (string) | null;
    loadingPortId?: number;
    loadingPort?: (string) | null;
    currency?: (string) | null;
    freeTime?: number;
    multiStop?: number;
    overtimeTariff?: number;
    unitTariff?: number;
    containerNames?: Array<(string)> | null;
    comment?: (string) | null;
    updated?: (string) | null;
    created?: string;
};

export type HaulagePostViewModel = {
    id?: (string) | null;
    haulierId?: number;
    haulierName?: (string) | null;
    validUntil?: string;
    currency?: (string) | null;
    loadingCity?: (string) | null;
    updated?: string;
    loadingPortId?: number;
    loadingPort?: (string) | null;
    freeTime?: number;
    multiStop?: number;
    overtimeTariff?: number;
    unitTariff?: number;
    haulageType?: (string) | null;
    emptyPickupDepot?: (string) | null;
    comment?: (string) | null;
    containers?: Array<PackageViewModel> | null;
};

export type HaulageSupplierViewModel = {
    id?: (string) | null;
    haulierName?: (string) | null;
    currency?: (string) | null;
    validUntil?: string;
    created?: string;
    freeTime?: number;
    multiStop?: number;
    overtimeTariff?: number;
    unitTariff?: number;
    haulageType?: (string) | null;
    emptyPickupDepot?: (string) | null;
    containersType?: Array<(string)> | null;
};

export type HaulageViewModel = {
    id?: (string) | null;
    haulierId?: number;
    haulierName?: (string) | null;
    validUntil?: string;
    created?: string;
    updated?: (string) | null;
    currency?: (string) | null;
    loadingCity?: (string) | null;
    loadingPortId?: number;
    loadingPort?: (string) | null;
    freeTime?: number;
    multiStop?: number;
    overtimeTariff?: number;
    unitTariff?: number;
    haulageType?: (string) | null;
    emptyPickupDepot?: (string) | null;
    comment?: (string) | null;
    containers?: Array<PackageViewModel> | null;
};

export type MiscellaneousContainer = {
    container?: Package;
    services?: Array<Service> | null;
};

export type MiscellaneousOfferViewModel = {
    id?: (string) | null;
    supplierName?: (string) | null;
    currency?: (string) | null;
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    comment?: (string) | null;
    updated?: (string) | null;
    created?: string;
    price20?: number;
    price40?: number;
    price20dry?: number;
    price20rf?: number;
    price40dry?: number;
    price40hc?: number;
    price40hcrf?: number;
    services?: Array<MiscellaneousServiceViewModel> | null;
    containers?: Array<MiscellaneousContainer> | null;
};

export type MiscellaneousServiceViewModel = {
    miscellaneousServiceId?: (string) | null;
    service?: ServiceViewModel;
    containers?: Array<PackageViewModel> | null;
};

export type MiscellaneousViewModel = {
    id?: (string) | null;
    departurePortId?: (number) | null;
    destinationPortId?: (number) | null;
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    supplierId?: number;
    supplierName?: (string) | null;
    validUntil?: string;
    updated?: (string) | null;
    created?: (string) | null;
    currency?: (string) | null;
    comment?: (string) | null;
    services?: Array<MiscellaneousServiceViewModel> | null;
    containers?: Array<MiscellaneousContainer> | null;
};

export type Package = {
    packageId?: number;
    packageName?: (string) | null;
};

export type PackageViewModel = {
    packageId?: number;
    packageName?: (string) | null;
};

export type SeaFreightContainer = {
    container?: Package;
    services?: Array<Service> | null;
};

export type SeaFreightOfferViewModel = {
    seaFreightId?: (string) | null;
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    validUntil?: (string) | null;
    carrierName?: (string) | null;
    carrierAgentName?: (string) | null;
    price20dry?: number;
    price20rf?: number;
    price40dry?: number;
    price40hc?: number;
    price40hcrf?: number;
    transitTime?: (number) | null;
    frequency?: (number) | null;
    currency?: (string) | null;
    comment?: (string) | null;
    lastUpdated?: (string) | null;
    created?: string;
    containers?: Array<SeaFreightContainer> | null;
};

export type SeaFreightServiceVieModel = {
    seaFreightServiceId?: (string) | null;
    service?: ServiceViewModel;
    containers?: Array<PackageViewModel> | null;
};

export type SeaFreightSupplierViewModel = {
    seaFreightId?: (string) | null;
    carrierAgentName?: (string) | null;
    transitTime?: (number) | null;
    frequency?: (number) | null;
    currency?: (string) | null;
    total20Dry?: number;
    total40Dry?: number;
    total20HCRF?: number;
    total40HC?: number;
    total20RF?: number;
    validUntil?: string;
    created?: string;
    containers?: Array<SeaFreightContainer> | null;
};

export type SeaFreightsViewModel = {
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    validCount?: number;
    suppliers?: Array<SeaFreightSupplierViewModel> | null;
};

export type SeaFreightViewModel = {
    seaFreightId?: (string) | null;
    departurePortId?: number;
    destinationPortId?: number;
    departurePortName?: (string) | null;
    destinationPortName?: (string) | null;
    carrierId?: number;
    lastUpdated?: string;
    carrierName?: (string) | null;
    carrierAgentId?: number;
    carrierAgentName?: (string) | null;
    currency?: (string) | null;
    validUntil?: string;
    transitTime?: (number) | null;
    frequency?: (number) | null;
    comment?: (string) | null;
    services?: Array<SeaFreightServiceVieModel> | null;
};

export type Service = {
    serviceId?: number;
    serviceName?: (string) | null;
    price?: number;
};

export type ServiceViewModel = {
    serviceId?: number;
    serviceName?: (string) | null;
    price?: number;
    containers?: Array<PackageViewModel> | null;
};

export type PostApiHaulageHaulageData = {
    body?: HaulagePostViewModel;
};

export type PostApiHaulageHaulageResponse = (string);

export type PostApiHaulageHaulageError = unknown;

export type GetApiHaulageHaulageData = {
    query?: {
        offerId?: string;
    };
};

export type GetApiHaulageHaulageResponse = (HaulageViewModel);

export type GetApiHaulageHaulageError = unknown;

export type GetApiHaulageHaulagesData = {
    query?: {
        ContainerIdsType?: Array<(number)>;
        EmptyPickupDepot?: string;
        HaulageType?: string;
        HaulierId?: number;
        LoadingCity?: string;
        LoadingPortId?: number;
    };
};

export type GetApiHaulageHaulagesResponse = (Array<HaulageGridGetViewModel>);

export type GetApiHaulageHaulagesError = unknown;

export type DeleteApiHaulageDeleteHaulageData = {
    query?: {
        offerId?: string;
    };
};

export type DeleteApiHaulageDeleteHaulageResponse = (boolean);

export type DeleteApiHaulageDeleteHaulageError = unknown;

export type GetApiMiscellaneousMiscellaneousData = {
    query?: {
        departurePortId?: number;
        destinationPortId?: number;
        id?: string;
        supplierId?: number;
        withShipment?: boolean;
    };
};

export type GetApiMiscellaneousMiscellaneousResponse = (unknown);

export type GetApiMiscellaneousMiscellaneousError = unknown;

export type PostApiMiscellaneousMiscellaneousData = {
    body?: MiscellaneousViewModel;
};

export type PostApiMiscellaneousMiscellaneousResponse = (unknown);

export type PostApiMiscellaneousMiscellaneousError = unknown;

export type DeleteApiMiscellaneousDeleteMiscellaneousByIdData = {
    path: {
        id: string;
    };
};

export type DeleteApiMiscellaneousDeleteMiscellaneousByIdResponse = (unknown);

export type DeleteApiMiscellaneousDeleteMiscellaneousByIdError = unknown;

export type GetApiPricingHaulagesOfferRequestData = {
    query?: {
        ContainerIdsType?: Array<(number)>;
        HaulageType?: string;
        LoadingCity?: string;
        LoadingPortId?: number;
        PlannedDeparture?: string;
    };
};

export type GetApiPricingHaulagesOfferRequestResponse = (Array<HaulageOfferViewModel>);

export type GetApiPricingHaulagesOfferRequestError = unknown;

export type GetApiPricingMiscellaneoussOffersRequestData = {
    query?: {
        ContainerTypesId?: Array<(number)>;
        DeparturePortId?: number;
        DestinationPortId?: number;
        Package20?: boolean;
        Package40?: boolean;
        PlannedDeparture?: string;
    };
};

export type GetApiPricingMiscellaneoussOffersRequestResponse = (Array<MiscellaneousOfferViewModel>);

export type GetApiPricingMiscellaneoussOffersRequestError = unknown;

export type GetApiPricingSeaFreightsOffersRequestData = {
    query?: {
        ContainerTypesId?: Array<(number)>;
        DeparturePortId?: number;
        DestinationPortId?: number;
        PlannedDeparture?: string;
    };
};

export type GetApiPricingSeaFreightsOffersRequestResponse = (Array<SeaFreightOfferViewModel>);

export type GetApiPricingSeaFreightsOffersRequestError = unknown;

export type PostApiSeaFreightSeaFreightData = {
    body?: SeaFreightViewModel;
};

export type PostApiSeaFreightSeaFreightResponse = (unknown);

export type PostApiSeaFreightSeaFreightError = unknown;

export type GetApiSeaFreightSeaFreightData = {
    query?: {
        seaFreightId?: string;
    };
};

export type GetApiSeaFreightSeaFreightResponse = (SeaFreightViewModel);

export type GetApiSeaFreightSeaFreightError = unknown;

export type GetApiSeaFreightGetSeaFreightsData = {
    query?: {
        CarrierAgentId?: number;
        DeparturePortId?: number;
        DestinationPortId?: number;
    };
};

export type GetApiSeaFreightGetSeaFreightsResponse = (Array<SeaFreightsViewModel>);

export type GetApiSeaFreightGetSeaFreightsError = unknown;

export type DeleteApiSeaFreightDeleteSeaFreightPriceData = {
    query?: {
        id?: string;
    };
};

export type DeleteApiSeaFreightDeleteSeaFreightPriceResponse = (boolean);

export type DeleteApiSeaFreightDeleteSeaFreightPriceError = unknown;