// This file is auto-generated by @hey-api/openapi-ts

export type Assignee = {
    id?: number;
    name: string;
    email: string;
    idUser?: (string) | null;
};

export type CargoDetailsViewModel = {
    packageId?: number;
    packageName?: (string) | null;
    quantity?: number;
    products?: Array<RequestQuoteProductViewModel> | null;
};

export type ChangeStatusRequest = {
    newStatus?: StatusRequest;
    customMessage?: (string) | null;
};

export type EmailConfig = {
    id?: number;
    adminEmail: string;
    fromEmail: string;
};

export type GraphApiUser = {
    id?: (string) | null;
};

export type HSCodeLIS = {
    hS_Code?: number;
    _4_digit_categories?: (string) | null;
    product_description_En?: (string) | null;
    product_description_Fr?: (string) | null;
    product_description_NL?: (string) | null;
};

export type HSCodeViewModel = {
    productId?: string;
    productName?: (string) | null;
    productName_FR?: (string) | null;
    productName_NL?: (string) | null;
};

export enum NoteType {
    AUTOMATIC = 'Automatic',
    GENERAL = 'General',
    CUSTOM_STATUS_CHANGE = 'CustomStatusChange',
    INFORMATION_REQUEST = 'InformationRequest'
}

export type RequestQuoteBaseViewModel = {
    requestQuoteId?: string;
    trackingNumber?: (string) | null;
    customerName?: (string) | null;
    departure?: (string) | null;
    arrival?: (string) | null;
    status?: StatusEnum;
    assigneeName?: (string) | null;
    created?: Date;
};

export type RequestQuoteHistory = {
    id?: number;
    requestQuoteId: number;
    assigneeId?: (number) | null;
    assignee?: Assignee;
    assignedAt?: Date;
    unassignedAt?: (Date) | null;
};

export type RequestQuoteNote = {
    id?: number;
    content?: (string) | null;
    createdAt?: Date;
    requestQuoteId?: number;
    isInternal?: boolean;
    noteType?: NoteType;
    subject?: (string) | null;
    email?: (string) | null;
    idUser?: (string) | null;
};

export type RequestQuoteProductViewModel = {
    productId?: (number) | null;
    productName?: (string) | null;
};

export type RequestQuoteViewModel = {
    requestQuoteId?: string;
    trackingNumber?: (string) | null;
    customerName?: (string) | null;
    departure?: (string) | null;
    arrival?: (string) | null;
    status?: StatusEnum;
    assigneeName?: (string) | null;
    created?: Date;
    customerId?: number;
    cellPhone?: (string) | null;
    hasWhatsapp?: boolean;
    email?: (string) | null;
    departureId?: number;
    arrivalId?: number;
    cargoDetails?: Array<CargoDetailsViewModel> | null;
    assignee?: string;
    lastUpdated?: (Date) | null;
    comment?: (string) | null;
};

export enum StatusEnum {
    NEW = 'NEW',
    PENDING = 'PENDING',
    VALID = 'VALID',
    REJECT = 'REJECT',
    BLOCKED = 'BLOCKED'
}

export enum StatusRequest {
    NEW = 'New',
    EN_ATTENTE = 'EnAttente',
    VALIDER = 'Valider',
    REJETER = 'Rejeter',
    EN_COURS_DE_TRAITEMENT = 'EnCoursDeTraitement',
    EN_TRANSIT = 'EnTransit',
    EN_DOUANE = 'EnDouane',
    LIVRAISON_EN_COURS = 'LivraisonEnCours',
    LIVRE = 'Livre',
    ANNULE = 'Annule',
    RETOUR = 'Retour',
    PROBLÈME = 'Problème',
    EN_ATTENTE_DE_FACTURATION = 'EnAttenteDeFacturation'
}

export type GetApiAssigneeData = {
    query?: {
        nameFilter?: string;
        userIdFilter?: string;
    };
};

export type GetApiAssigneeResponse = (Array<Assignee>);

export type GetApiAssigneeError = unknown;

export type PostApiAssigneeData = {
    body?: Assignee;
};

export type PostApiAssigneeResponse = (Assignee);

export type PostApiAssigneeError = unknown;

export type GetApiAssigneeByIdData = {
    path: {
        id: number;
    };
};

export type GetApiAssigneeByIdResponse = (Assignee);

export type GetApiAssigneeByIdError = unknown;

export type PutApiAssigneeByIdData = {
    body?: Assignee;
    path: {
        id: number;
    };
};

export type PutApiAssigneeByIdResponse = (unknown);

export type PutApiAssigneeByIdError = unknown;

export type DeleteApiAssigneeByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiAssigneeByIdResponse = (unknown);

export type DeleteApiAssigneeByIdError = unknown;

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdData = {
    path: {
        assigneeId: number;
        requestQuoteId: number;
    };
};

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdResponse = (unknown);

export type PutApiAssigneeByRequestQuoteIdByAssigneeIdError = unknown;

export type PutApiAssigneeUnassignByRequestQuoteIdData = {
    path: {
        requestQuoteId: number;
    };
};

export type PutApiAssigneeUnassignByRequestQuoteIdResponse = (unknown);

export type PutApiAssigneeUnassignByRequestQuoteIdError = unknown;

export type PostApiEmailData = {
    body?: {
        From?: string;
        To?: string;
        Subject?: string;
        HtmlContent?: string;
        Attachments?: Array<((Blob | File))>;
    };
};

export type PostApiEmailResponse = (unknown);

export type PostApiEmailError = unknown;

export type GetEmailConfigResponse = (unknown);

export type GetEmailConfigError = unknown;

export type PutEmailConfigData = {
    body?: EmailConfig;
};

export type PutEmailConfigResponse = (unknown);

export type PutEmailConfigError = unknown;

export type PostEmailConfigData = {
    body?: EmailConfig;
};

export type PostEmailConfigResponse = (unknown);

export type PostEmailConfigError = unknown;

export type PostApiFileUploadData = {
    body?: {
        file?: (Blob | File);
    };
};

export type PostApiFileUploadResponse = (unknown);

export type PostApiFileUploadError = unknown;

export type GetApiFileByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type GetApiFileByBlobNameResponse = (unknown);

export type GetApiFileByBlobNameError = unknown;

export type DeleteApiFileByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type DeleteApiFileByBlobNameResponse = (unknown);

export type DeleteApiFileByBlobNameError = unknown;

export type GetApiFileUriByBlobNameData = {
    path: {
        blobName: string;
    };
};

export type GetApiFileUriByBlobNameResponse = (unknown);

export type GetApiFileUriByBlobNameError = unknown;

export type GetApiHsCodeLisResponse = (Array<HSCodeViewModel>);

export type GetApiHsCodeLisError = (unknown);

export type PostApiHsCodeLisData = {
    body?: HSCodeLIS;
};

export type PostApiHsCodeLisResponse = (HSCodeLIS);

export type PostApiHsCodeLisError = unknown;

export type GetApiHsCodeLisByIdData = {
    path: {
        id: number;
    };
};

export type GetApiHsCodeLisByIdResponse = (HSCodeLIS);

export type GetApiHsCodeLisByIdError = unknown;

export type PutApiHsCodeLisByIdData = {
    body?: HSCodeLIS;
    path: {
        id: number;
    };
};

export type PutApiHsCodeLisByIdResponse = (unknown);

export type PutApiHsCodeLisByIdError = unknown;

export type DeleteApiHsCodeLisByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiHsCodeLisByIdResponse = (unknown);

export type DeleteApiHsCodeLisByIdError = unknown;

export type PostApiRequestNewData = {
    body?: RequestQuoteViewModel;
};

export type PostApiRequestNewResponse = ({
    [key: string]: (string);
});

export type PostApiRequestNewError = (unknown);

export type GetApiRequestResponse = (Array<RequestQuoteBaseViewModel>);

export type GetApiRequestError = (unknown);

export type GetApiRequestByIdData = {
    path: {
        id: string;
    };
};

export type GetApiRequestByIdResponse = (RequestQuoteViewModel);

export type GetApiRequestByIdError = (unknown);

export type DeleteApiRequestByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestByIdResponse = (unknown);

export type DeleteApiRequestByIdError = unknown;

export type PutApiRequestUpdateByIdData = {
    body?: RequestQuoteViewModel;
    path: {
        id: string;
    };
};

export type PutApiRequestUpdateByIdResponse = (unknown);

export type PutApiRequestUpdateByIdError = (unknown);

export type PutApiRequestByIdChangeStatusData = {
    body?: ChangeStatusRequest;
    path: {
        id: number;
    };
};

export type PutApiRequestByIdChangeStatusResponse = (unknown);

export type PutApiRequestByIdChangeStatusError = unknown;

export type GetApiRequestQuoteHistoryData = {
    query?: {
        assigneeId?: number;
        endDate?: Date;
        requestQuoteId?: number;
        startDate?: Date;
    };
};

export type GetApiRequestQuoteHistoryResponse = (unknown);

export type GetApiRequestQuoteHistoryError = unknown;

export type PostApiRequestQuoteHistoryData = {
    body?: RequestQuoteHistory;
};

export type PostApiRequestQuoteHistoryResponse = (unknown);

export type PostApiRequestQuoteHistoryError = unknown;

export type GetApiRequestQuoteHistoryByIdData = {
    path: {
        id: number;
    };
};

export type GetApiRequestQuoteHistoryByIdResponse = (unknown);

export type GetApiRequestQuoteHistoryByIdError = unknown;

export type PutApiRequestQuoteHistoryByIdData = {
    body?: RequestQuoteHistory;
    path: {
        id: number;
    };
};

export type PutApiRequestQuoteHistoryByIdResponse = (unknown);

export type PutApiRequestQuoteHistoryByIdError = unknown;

export type DeleteApiRequestQuoteHistoryByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestQuoteHistoryByIdResponse = (unknown);

export type DeleteApiRequestQuoteHistoryByIdError = unknown;

export type GetApiRequestQuoteNotesData = {
    query?: {
        createdAtFrom?: Date;
        createdAtTo?: Date;
        isInternal?: boolean;
        noteType?: NoteType;
        requestQuoteId?: number;
        userIdFilter?: string;
    };
};

export type GetApiRequestQuoteNotesResponse = (unknown);

export type GetApiRequestQuoteNotesError = unknown;

export type PostApiRequestQuoteNotesData = {
    body?: RequestQuoteNote;
};

export type PostApiRequestQuoteNotesResponse = (unknown);

export type PostApiRequestQuoteNotesError = unknown;

export type GetApiRequestQuoteNotesByIdData = {
    path: {
        id: number;
    };
};

export type GetApiRequestQuoteNotesByIdResponse = (unknown);

export type GetApiRequestQuoteNotesByIdError = unknown;

export type PutApiRequestQuoteNotesByIdData = {
    body?: RequestQuoteNote;
    path: {
        id: number;
    };
};

export type PutApiRequestQuoteNotesByIdResponse = (unknown);

export type PutApiRequestQuoteNotesByIdError = unknown;

export type DeleteApiRequestQuoteNotesByIdData = {
    path: {
        id: number;
    };
};

export type DeleteApiRequestQuoteNotesByIdResponse = (unknown);

export type DeleteApiRequestQuoteNotesByIdError = unknown;

export type PostApiSmsSendData = {
    query?: {
        fromPhoneNumber?: string;
        messageText?: string;
        toPhoneNumber?: string;
    };
};

export type PostApiSmsSendResponse = (unknown);

export type PostApiSmsSendError = unknown;

export type GetApiTrackingByTrackingNumberData = {
    path: {
        trackingNumber: string;
    };
};

export type GetApiTrackingByTrackingNumberResponse = (unknown);

export type GetApiTrackingByTrackingNumberError = unknown;

export type PostUserGroupUsersByUserIdData = {
    path: {
        userId: string;
    };
};

export type PostUserGroupUsersByUserIdResponse = (unknown);

export type PostUserGroupUsersByUserIdError = unknown;

export type DeleteUserGroupUsersByUserIdData = {
    path: {
        userId: string;
    };
};

export type DeleteUserGroupUsersByUserIdResponse = (unknown);

export type DeleteUserGroupUsersByUserIdError = unknown;

export type GetUserGroupUsersResponse = (Array<GraphApiUser>);

export type GetUserGroupUsersError = unknown;

export type PostWhatsAppSendmessageData = {
    query?: {
        fromWhatsAppNumber?: string;
        messageText?: string;
        toPhoneNumber?: string;
    };
};

export type PostWhatsAppSendmessageResponse = (unknown);

export type PostWhatsAppSendmessageError = unknown;

export type GetApiRequestResponseTransformer = (data: any) => Promise<GetApiRequestResponse>;

export type RequestQuoteBaseViewModelModelResponseTransformer = (data: any) => RequestQuoteBaseViewModel;

export const RequestQuoteBaseViewModelModelResponseTransformer: RequestQuoteBaseViewModelModelResponseTransformer = data => {
    if (data?.created) {
        data.created = new Date(data.created);
    }
    return data;
};

export const GetApiRequestResponseTransformer: GetApiRequestResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(RequestQuoteBaseViewModelModelResponseTransformer);
    }
    return data;
};

export type GetApiRequestByIdResponseTransformer = (data: any) => Promise<GetApiRequestByIdResponse>;

export type RequestQuoteViewModelModelResponseTransformer = (data: any) => RequestQuoteViewModel;

export const RequestQuoteViewModelModelResponseTransformer: RequestQuoteViewModelModelResponseTransformer = data => {
    if (data?.created) {
        data.created = new Date(data.created);
    }
    if (data?.lastUpdated) {
        data.lastUpdated = new Date(data.lastUpdated);
    }
    return data;
};

export const GetApiRequestByIdResponseTransformer: GetApiRequestByIdResponseTransformer = async (data) => {
    RequestQuoteViewModelModelResponseTransformer(data);
    return data;
};