/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export type GetApiMiscellaneousMiscellaneousParams = {
id?: string;
withShipment?: boolean;
departurePortId?: number;
destinationPortId?: number;
supplierId?: number;
};
