/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export type GetApiPricingHaulagesOfferRequestParams = {
PlannedDeparture?: string;
LoadingCity?: string;
HaulageType?: string;
LoadingPortId?: number;
ContainerIdsType?: number[];
};
