/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export type GetApiPricingMiscellaneoussOffersRequestParams = {
DeparturePortId?: number;
DestinationPortId?: number;
PlannedDeparture?: string;
ContainerTypesId?: number[];
Package20?: boolean;
Package40?: boolean;
};
