/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export type GetApiHaulageHaulagesParams = {
LoadingCity?: string;
LoadingPortId?: number;
HaulierId?: number;
HaulageType?: string;
EmptyPickupDepot?: string;
ContainerIdsType?: number[];
};
