/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export interface HaulageSupplierViewModel {
  /** @nullable */
  containersType?: string[] | null;
  created?: string;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  emptyPickupDepot?: string | null;
  freeTime?: number;
  /** @nullable */
  haulageType?: string | null;
  /** @nullable */
  haulierName?: string | null;
  /** @nullable */
  id?: string | null;
  multiStop?: number;
  overtimeTariff?: number;
  unitTariff?: number;
  validUntil?: string;
}
