/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { PackageViewModel } from './packageViewModel';

export interface HaulageViewModel {
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  containers?: PackageViewModel[] | null;
  created?: string;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  emptyPickupDepot?: string | null;
  freeTime?: number;
  /** @nullable */
  haulageType?: string | null;
  haulierId?: number;
  /** @nullable */
  haulierName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  loadingCity?: string | null;
  /** @nullable */
  loadingPort?: string | null;
  loadingPortId?: number;
  multiStop?: number;
  overtimeTariff?: number;
  unitTariff?: number;
  /** @nullable */
  updated?: string | null;
  validUntil?: string;
}
