/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { HaulageSupplierViewModel } from './haulageSupplierViewModel';

export interface HaulageGridGetViewModel {
  /** @nullable */
  hauliers?: HaulageSupplierViewModel[] | null;
  /** @nullable */
  loadingCity?: string | null;
  /** @nullable */
  loadingPort?: string | null;
}
