/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { MiscellaneousContainer } from './miscellaneousContainer';
import type { MiscellaneousServiceViewModel } from './miscellaneousServiceViewModel';

export interface MiscellaneousViewModel {
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  containers?: MiscellaneousContainer[] | null;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  departurePortId?: number | null;
  /** @nullable */
  departurePortName?: string | null;
  /** @nullable */
  destinationPortId?: number | null;
  /** @nullable */
  destinationPortName?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  services?: MiscellaneousServiceViewModel[] | null;
  supplierId?: number;
  /** @nullable */
  supplierName?: string | null;
  /** @nullable */
  updated?: string | null;
  validUntil?: string;
}
