/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { MiscellaneousContainer } from './miscellaneousContainer';
import type { MiscellaneousServiceViewModel } from './miscellaneousServiceViewModel';

export interface MiscellaneousOfferViewModel {
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  containers?: MiscellaneousContainer[] | null;
  created?: string;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  departurePortName?: string | null;
  /** @nullable */
  destinationPortName?: string | null;
  /** @nullable */
  id?: string | null;
  price20?: number;
  price20dry?: number;
  price20rf?: number;
  price40?: number;
  price40dry?: number;
  price40hc?: number;
  price40hcrf?: number;
  /** @nullable */
  services?: MiscellaneousServiceViewModel[] | null;
  /** @nullable */
  supplierName?: string | null;
  /** @nullable */
  updated?: string | null;
}
