/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { SeaFreightContainer } from './seaFreightContainer';

export interface SeaFreightSupplierViewModel {
  /** @nullable */
  carrierAgentName?: string | null;
  /** @nullable */
  containers?: SeaFreightContainer[] | null;
  created?: string;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  frequency?: number | null;
  /** @nullable */
  seaFreightId?: string | null;
  total20Dry?: number;
  total20HCRF?: number;
  total20RF?: number;
  total40Dry?: number;
  total40HC?: number;
  /** @nullable */
  transitTime?: number | null;
  validUntil?: string;
}
