/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { SeaFreightContainer } from './seaFreightContainer';

export interface SeaFreightOfferViewModel {
  /** @nullable */
  carrierAgentName?: string | null;
  /** @nullable */
  carrierName?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  containers?: SeaFreightContainer[] | null;
  created?: string;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  departurePortName?: string | null;
  /** @nullable */
  destinationPortName?: string | null;
  /** @nullable */
  frequency?: number | null;
  /** @nullable */
  lastUpdated?: string | null;
  price20dry?: number;
  price20rf?: number;
  price40dry?: number;
  price40hc?: number;
  price40hcrf?: number;
  /** @nullable */
  seaFreightId?: string | null;
  /** @nullable */
  transitTime?: number | null;
  /** @nullable */
  validUntil?: string | null;
}
