/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { Package } from './package';
import type { Service } from './service';

export interface SeaFreightContainer {
  container?: Package;
  /** @nullable */
  services?: Service[] | null;
}
