/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { PackageViewModel } from './packageViewModel';
import type { ServiceViewModel } from './serviceViewModel';

export interface SeaFreightServiceVieModel {
  /** @nullable */
  containers?: PackageViewModel[] | null;
  /** @nullable */
  seaFreightServiceId?: string | null;
  service?: ServiceViewModel;
}
