/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */

export interface Service {
  price?: number;
  serviceId?: number;
  /** @nullable */
  serviceName?: string | null;
}
