/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * LIS PRICING API
 * OpenAPI spec version: v1
 */
import type { PackageViewModel } from './packageViewModel';

export interface ServiceViewModel {
  /** @nullable */
  containers?: PackageViewModel[] | null;
  price?: number;
  serviceId?: number;
  /** @nullable */
  serviceName?: string | null;
}
